---
- hosts: all
  become: true
  tasks:
   - name: apt-update
     apt:
      update_cache: yes
   - name: Install Docker
     apt:
      name: docker.io
      state: present
   - name: Run Docker Container
     command: chdir= docker run -it -d -p 8085:5000 anjurose/test:latest
